### ISSUE TITLE
Header in the ISO message

### ISSUE THREAD

**Issue by danicaliforrnia** [keyhan/jBSBE#5]
Hi keyhan,

Does it work with headers?

I'm trying to implement jreactive-8583 but when I specify headers for my message types I always get this exception:

`java.text.ParseException: ISO8583 MessageFactory has no parsing guide for message type 1b3f0`

It seems to be related with j8583 library.

**Comment by keyhan** [comment]
Hi, I have not touched this code for a long time so I am not sure. From your message it seems the problem is in j8583 library.
Since I have not updated this for a long while it could be so that you can fork this and update to the latest j8583 and the problem could have been fixed.
My goal was that build this into jreactive but since I am not working with ISO8583 anymore someone else should take on the task :-).
